import AestheticIcon from "./aesthetic";
import CultureIcon from "./culture";
import AddIcon from "./add";
import GouvIcon from "./gouv";
import KodamaIcon from "./kodama";
import Kodama2Icon from "./kodama2";
import ParamIcon from "./param";
import MarketIcon from "./market";
import FoodIcon from "./food";
import TransportIcon from "./transport";
import HomeIcon from "./home";
import SmokeIcon from "./smoke";
import ArrowIcon from "./arrow";
export { AestheticIcon, ArrowIcon, CultureIcon, AddIcon, GouvIcon, KodamaIcon, Kodama2Icon, ParamIcon, MarketIcon, FoodIcon, TransportIcon, HomeIcon, SmokeIcon };
