export const container: string;
export const picture: string;
export const content: string;
export const data: string;
export const name: string;
export const balance: string;
export const amount: string;
export const goal: string;
export const progress: string;
